name: Properties Version bump-up
description: 'Change the version in the specified properties file to the next snapshot'
inputs:
  version_file:
    description: 'The properties file containing the version info'
    required: true
  version_key:
    description: 'The key of the version value. By default: `version`'
    required: false
    default: 'version'
  version_value:
    description: 'The current version in the file. By default: `env.VERSION_VALUE`'
    required: false
    default: ${{ env.VERSION_VALUE }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version_file }}
    - ${{ inputs.version_key }}
    - ${{ inputs.version_value }}

outputs:
  next_version:
    description: 'The next snapshot version now placed on the properties file'

branding:
  icon: 'file-plus'
  color: blue